source 'https://github.com/CocoaPods/Specs.git'

target 'ios-navigation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-navigation
  pod 'SnapKit', '~> 5.6.0'

end

target 'StorageService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StorageService

end
